services:
  sfw-chinese-feed:
    container_name: sfw-chinese-feed
    image: ghcr.io/leverglowh/sfw-chinese-bsky-feed:latest
    restart: always
    ports:
      - "6688:6688"
    env_file: .env
    volumes:
      - ./data:/usr/src/app/data
