name: DB Backup

on:
  schedule:
    - cron: '0 0 * * *'  # Daily at midnight
env:
  CONTAINER_NAME: sfw-chinese-feed

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH agent
        id: ssh-agent
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            mkdir -p /root/backup
            # docker stop ${{ env.CONTAINER_NAME }} || true
            sqlite3 /root/bskyfeed/data/db.sqlite '.backup '/root/backup/db-$(date +%Y%m%d).sqlite''
            # docker start ${{ env.CONTAINER_NAME }} || true
            find /root/backup -type f -name 'db-*.sqlite' -mtime +7 -exec rm {} \;
